name: Build, test and publish NuGets

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/build_test_and_publish.yml'      

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.202'
      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run:  dotnet test --logger "trx;LogFileName=test-results.trx"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: "**/test-results.trx"                            
          reporter: dotnet-trx
          fail-on-error: true
          
      - name: Publish
        run: |
          dotnet pack -c Release
          dotnet nuget add source --username dmunch --name github "https://nuget.pkg.github.com/dmunch/index.json"
          dotnet nuget push "src/**/bin/Release/biscuit_net.*.nupkg" --source github --api-key ${{ secrets.GITHUB_TOKEN }}